# Generated by Django 2.2.7 on 2020-04-04 13:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('datathon', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['level__level']},
        ),
        migrations.RemoveField(
            model_name='question',
            name='prerequisites',
        ),
        migrations.AddField(
            model_name='team',
            name='bonus_points',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='question',
            name='dataset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='datathon.Dataset'),
        ),
        migrations.AlterField(
            model_name='team',
            name='questions',
            field=models.ManyToManyField(blank=True, to='datathon.Question'),
        ),
    ]
