# Generated by Django 2.2.7 on 2020-04-04 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datathon', '0004_teamdataset'),
    ]

    operations = [
        migrations.AddField(
            model_name='level',
            name='color',
            field=models.CharField(default='blue', max_length=20),
            preserve_default=False,
        ),
    ]
