# Generated by Django 2.2.7 on 2020-04-05 18:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('datathon', '0005_level_color'),
    ]

    operations = [
        migrations.CreateModel(
            name='BonusScore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.DecimalField(decimal_places=3, default=0, max_digits=4)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bonus_scores', to='datathon.Dataset')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bonus_scores', to='datathon.Team')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
