# Generated by Django 2.2.7 on 2020-04-09 04:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datathon', '0008_auto_20200406_0824'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='bonus_points',
        ),
    ]
