# Generated by Django 2.2.7 on 2020-04-09 05:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datathon', '0009_remove_team_bonus_points'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bonusscore',
            name='score',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=4, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
