# Generated by Django 2.2.7 on 2020-04-11 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datathon', '0010_auto_20200409_0527'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='team',
            options={'ordering': ['points']},
        ),
    ]
